# Generated by Django 5.0.6 on 2024-07-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
