# Generated by Django 5.0.6 on 2024-07-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0005_remove_customuser_role_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
