# Generated by Django 5.0.6 on 2024-07-07 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrequest',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
