# Generated by Django 5.0.6 on 2024-07-07 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedicalApp', '0007_remove_customerrequest_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
